### ISSUE TITLE
Bug with text styling (bold, cursive, etc)

### ISSUE THREAD

**Issue by zaxovaiko** [zaxoavoki/internship-js-notepad#1] opened 2021-10-03 21:21 UTC
The notepad has a bug with text styling.

----
Steps to reproduce the bug:

 - Write a few lines of any text
 - Select any part of it
 - Go to the main menu and choose <kbd>Edit -> Bold/Cursive/Normal</kbd>
 - Repeat these steps a few more times

You will notice it does not work as it should.

Hint: take a look at `public/js/helpers.js` file, especially at `function setFontFormat(elem)`

**Comment by shikhar13012001** [comment] 2021-10-04 21:31
Can I try to work on this issue? Please assign this to me

**Comment by shikhar13012001** [comment] 2021-10-04 21:38
Just a clarification 
you need the same selected part to toggle ?
Like if you made it bold and then you reselect it and again make it bold it should go back to normal?
Could you explain the error more, I cant reproduce or notice anything unusual

**Comment by zaxovaiko** [comment] 2021-10-04 22:30
> Can I try to work on this issue? Please assign this to me

Sure. Check the video explanation [here](https://imgur.com/nLZSBHc). As you can see, after making some changes we can't really go back to the previous state of normal format. Also, after making text bolder or cursive it breaks to a new line.

Take a look at [`execCommand()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand), but this feature is deprecated.

**Comment by shikhar13012001** [comment] 2021-10-05 06:43
ok sir I will try to resolve it

**Closed as completed** 2021-10-07 09:33 UTC
Labels: bug, good first issue, hacktoberfest, hacktoberfest2021
